"use strict"; //使用嚴格模式

const {createApp} = Vue;
createApp({
  data() {
    return {
      books: [
        {
          ISBN: "16001",
          書名: "紅樓夢",
          作者: "石心寺",
          價格: "750",
          出版社: "知返",
          庫存: "9",
          類型: "文學",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczPUymPfxPh2YFqzUYpfXHR7o0O1fzvZqlnFaghV_iigdqWrYaOne1IYdY25YVgEmUGYa-2_X4dvulD4OLQqqssAx2ihzFWRjuTXD8A8aFda3sHSwmYJwgg6i6XJAhqiuCXrVw0LJVcuoYrgkMDYsvmg=w460-h580-s-no-gm?authuser=0",
          介紹: "  紅樓夢哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16002",
          書名: "三國演義",
          作者: "黃問游",
          價格: "540",
          出版社: "知返",
          庫存: "17",
          類型: "文學類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczN1nCBb0efX7PhLSHew8d5_wC32hipYvmUa8JOPLzB2e2oMNi6obo8ctyXxDbj81hh9SHZA-LwpVFzYbPS4Cpc_Z2W0lar0TGuiYyOFpHYdRbQ90uG3xyCS85oONUOyX9wq0l6hgNl1Y71bN4BtQaab=w460-h580-s-no-gm?authuser=0",
          介紹: "  三國演義哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16003",
          書名: "AI淘汰人類",
          作者: "兆品力",
          價格: "320",
          出版社: "知返",
          庫存: "13",
          類型: "科學類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczPL1Lt_iuvZ9RtLZvuQiOtpYf6eTDr2oDLFOiHSpu4hpo4WLEcQiqNVU5WBgWezAn1EwaXznKGl9KAG1yNusZ4h51UBaUWqOWHuf-shcmfh6FYOpIEW2M35Frqm-Lzc1OY0haS4UfvrchE2Hq2LS2Fr=w460-h580-s-no-gm?authuser=0",
          介紹: "    AI淘汰人類哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16004",
          書名: "大新浣",
          作者: "常遠卜兒",
          價格: "250",
          出版社: "知返",
          庫存: "0",
          類型: "生活與休閒類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczPlwoUJ6FbyU7wYDEGY-Nmx28MxEPMKUMSk37MyF4O_xX6XRQKoi8_uGu-3mUaPTg1fjPrmCCnB_0_qvUH7WCOCK7hvC-IADxaV4tYjwPq__HftYKJrzbzaz6ysHoIyeQ1Zj3sDOa9rEn8HoMWpYhLv=w460-h580-s-no-gm?authuser=0",
          介紹: "    大新浣哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16005",
          書名: "騭菓",
          作者: "秋葉戊",
          價格: "390",
          出版社: "知返",
          庫存: "6",
          類型: "文學",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczNahsjrAx0sxHiMxkJIcQYWRGfA5WeZGMEKnZrFSiC6l6wgDkyYsjOkwVWr8ZWsRdBQq9itl70w7hCeRE0yiOXi6NLVBoXme_ns7GD3UYZrCrvTDTdbNNQCs4x2C0HggkY9-A6Kg2NIaGO-KI5Ng7pQ=w460-h580-s-no-gm?authuser=0",
          介紹: "    騭菓哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16006",
          書名: "寒山呼喚",
          作者: "昔布祖",
          價格: "180",
          出版社: "知返",
          庫存: "5",
          類型: "社會科學類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczP4tSwO7MOhekudPQTa-Kj4BwGZSWRY1jK_gyEAk65LIN4Xj0D5tfGQQcIKWnvQdh56FtfNSInupOOgiObVvRJJjxtI_PTxtzu6OB27IaUzKdDhfJu9FcyeIqI0l5P4JSo05_Nb7aa9XEc_9inFsKn-=w460-h580-s-no-gm?authuser=0",
          介紹: "    寒山呼喚哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16007",
          書名: "稻來帝",
          作者: "石村二",
          價格: "425",
          出版社: "知返",
          庫存: "7",
          類型: "宗教與哲學",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczNXc-_HLmLEAFRPQzekOqTdB1slxQGUNUdD3GiVl4hVOljHmuvfPMKQJspojAJfW6cT4Zn1euH4cxjnhjW7UAe9p8MrO6Qx7aQkE5eTwvWjB0KpAsoJFpj3Pu66AI4A_LegFOIjAFSB_5mvwVj980vi=w460-h580-s-no-gm?authuser=0",
          介紹: "    稻來帝哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16008",
          書名: "舊石戲",
          作者: "即子她",
          價格: "450",
          出版社: "知返",
          庫存: "11",
          類型: "生活與休閒類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczP2P4mBbmfEctz9z3GhIHcCjqBlbk1Md39Js-qqv932sqkU3CacvjBk22PIOry55YBqUe1fCeEg-dg7IEJmDDEhN0N7cLwRUPuH9NHwbkynJi-O4sgFYLyiXefzX7GbU-O-0Ljf6bqG4zxncb79ZFow=w460-h580-s-no-gm?authuser=0",
          介紹: "    舊石戲哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16009",
          書名: "墚由",
          作者: "兔幸和",
          價格: "390",
          出版社: "知返",
          庫存: "2",
          類型: "商業與管理",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczOHMb9o34Xqa38-h0poahL0wngKLgeOfLcNbanwukIqQnTBu5_HnZsfBI6gBGAubmIEOMKHvp-1-zYiw4eMogdCSb0lgdjyyevnbTm_KO3A-Fj_teM6MDfhnO0lrXnPgoq4F6CLigCcXPRSXrV5hHcr=w460-h580-s-no-gm?authuser=0",
          介紹: "    墚由哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16010",
          書名: "水中泉涓",
          作者: "祖抓吃",
          價格: "550",
          出版社: "知返",
          庫存: "9",
          類型: "文學",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczNGzZmS2g8XVsuAbL7vJy5d142k7pFlmxW978vl7IokzwTidV9nKAuGUeMOAwIVPrsx0B7o2MLnQIXm_WrYy4J5cddQQIJ0-qxhVtir2EFzl9vmD01geUDx7S7ZYVDg-mZD_wn_OK_LKCkAUzny76o9=w460-h580-s-no-gm?authuser=0",
          介紹: "    水中泉涓哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16011",
          書名: "故林匙",
          作者: "因貓免",
          價格: "880",
          出版社: "知返",
          庫存: "7",
          類型: "社會科學類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczMAhi6C2stnXlZMXFtKMha-A8_W5js_irVj5a4ms44l2IvrVVpWZExln9yMBv1uBAb-zLiqaiGp_5ee9t6qfsH56AOCIffg7wvrROFqg8iNzh5KqUTd4lrRFTLsGSB5iv9-Jp_bhTTHU4nXj9fgHiYD=w460-h580-s-no-gm?authuser=0",
          介紹: "    故林匙哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16012",
          書名: "漠禪茅更雅",
          作者: "游良前",
          價格: "480",
          出版社: "知返",
          庫存: "4",
          類型: "生活與休閒類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczMrHzOMNEsK6Vs9UkvU2jeXGDtjWbrndrledLsOEfLoGBfLNqfwhf_MDtU2xkRItghHEW-vN2mhH4InWN6zgbg3uMJhebx5LeZKopzSWzaNBDKEfYXb1wueXduc7Nhh7AMUFdFaiC39GuCAIm3Nqbta=w460-h580-s-no-gm?authuser=0",
          介紹: "    漠禪茅更雅哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
        {
          ISBN: "16013",
          書名: "漁捕",
          作者: "七還幾",
          價格: "230",
          出版社: "知返",
          庫存: "1",
          類型: "社會科學類",
          網址: "https://lh3.googleusercontent.com/pw/AP1GczOVZFlQhtKm_C-NHJk3hxrDOwVz2BkjKUB_FaZwLZrSgXXokWmslaeI3H7cHb7s_nMfRmbW-_UxtY1809Z4DIH0HYPTXIs2-PSs4bphtOahPYS6HP5EqeOEazP8TruC-yDicZlN7aYFSadk_-hmgTEZ=w460-h580-s-no-gm?authuser=0",
          介紹: "    漁捕哭蝶火固正歡申共羽和尾由\n節姐一物事。校里要金竹田杯朋助綠干歡找，登許樹還入休哪眼示時知邊休節才小嗎給高肖？相開位里。燈唱已停。\\\n\n植根很害寸以知走山大毛。雪士裝去喜往室消路魚兌每實爪天棵果至。在友村。都樹公送化。雲裏相石拍已黃西哭因拍，抓良能相背英孝雪吃而假乍英習找月吃頁。七抱重象眼園小且共九地跑很怪几躲。\n\n夕荷南力月方收勿尾黃完往夕讀直化花北交。坡來屋右泉院禾弓；還雲兌虎十呢二很豆訴內貝高起麼筆筆「升力姐」瓜只時兔米畫乾會采刃的植呢乙果重？哪少位游頭平。\n\n鳥收者昌蝶了朵門胡寺故昌房爬：里故遠後菜害松婆己十美鴨記雲、杯這兄足才麼老跑父孝聲念師吉看丁冬飛細几，刀戊誰乾放兌戶，後杯百乍車哥戶。\n\n的言結第法得，水交工就屋視叫左花做。",
        },
      ],
      showPopup: false, //是否顯示彈出視窗
      // classObj: {titleNavClassification: true},
    };
  },

  // methods: {
  //   updateShowTitleNavClassification() {
  //     this.classObj.titleNavClassification = !this.classObj.titleNavClassification;
  //   },
  // },
}).mount("#app");
